const char* YOV_CORE = ""
"\n"
"Result :: struct {\n"
"    failed: Bool;\n"
"    message: String;\n"
"    code: Int;\n"
"}\n"
"\n"
"YovInfo :: struct {\n"
"    path: String;\n"
"    version: String;\n"
"    major: UInt;\n"
"    minor: UInt;\n"
"    revision: UInt;\n"
"}\n"
"\n"
"Type :: struct {\n"
"    name: String;\n"
"}\n"
"\n"
"Context :: struct {\n"
"    cd: String;\n"
"    script_dir: String;\n"
"    caller_dir: String;\n"
"    args: Array[String];\n"
"    types: Array[Type];\n"
"    seed: UInt;\n"
"}\n"
"\n"
"OSKind :: enum {\n"
"    Windows, Linux\n"
"}\n"
"\n"
"OS :: struct {\n"
"    kind: OSKind;\n"
"}\n"
"\n"
"RedirectStdout :: enum {\n"
"    Console, Ignore, Script, ImportEnv\n"
"}\n"
"\n"
"CallsContext :: struct {\n"
"    redirect_stdout: RedirectStdout;\n"
"}\n"
"\n"
"// Core\n"
"\n"
"Typeof  :: func(object: Any) -> Type;\n"
"Print   :: func(object: Any);\n"
"PrintLn :: func(object: Any);\n"
"Exit    :: func(exit_code: Int);\n"
"SetCD   :: func(cd: String) -> Result;\n"
"Assert  :: func(result: Bool) -> Result;\n"
"Failed  :: func(message: String, exit_code: Int) -> Result;\n"
"\n"
"SleepMs :: func(ms: UInt);\n"
"Sleep   :: func(sec: Float);\n"
"\n"
"Env          :: func(name: String) -> (value: String, result: Result);\n"
"EnvPath      :: func(name: String) -> (value: String, result: Result);\n"
"EnvPathArray :: func(name: String) -> (value: Array[String], result: Result);\n"
"\n"
"/*\n"
"ArrayMakeEmpty :: func[T](count: UInt) -> List[T];\n"
"\n"
"ListMakeEmpty          :: func[T](count: UInt) -> List[T];\n"
"ListAppendBack         :: func[T](dst: Array[T]&, src: Array[T]);\n"
"ListAppendFront        :: func[T](dst: Array[T]&, src: Array[T]);\n"
"ListAppendElementBack  :: func[T](dst: Array[T]&, src: T);\n"
"ListAppendElementFront :: func[T](dst: Array[T]&, src: T);\n"
"ListRemove             :: func[T](dst: Array[T]&, index: UInt);\n"
"ListUnorderedRemove    :: func[T](dst: Array[T]&, index: UInt);\n"
"*/\n"
"\n"
"ArrayAppendBack         :: func(dst: Any, src: Any);\n"
"// TODO: ArrayAppendFront        :: func(dst: Any, src: Any);\n"
"ArrayAppendElementBack  :: func(dst: Any, src: Any);\n"
"// TODO: ArrayAppendElementFront :: func(dst: Any, src: Any);\n"
"ArrayRemove :: func(dst: Any, index: UInt);\n"
"ArrayUnorderedRemove :: func(dst: Any, index: UInt);\n"
"\n"
"ArrayMakeEmpty :: func(base_type: Type, dimensions: Array[UInt]) -> Any;\n"
"\n"
"ListMakeEmpty :: func(base_type: Type, dimensions: Array[UInt]) -> Any;\n"
"\n"
"// Console\n"
"\n"
"ANSI_CLEAR       : String : \"\\x1b[2J\";\n"
"ANSI_HOME        : String : \"\\x1b[H\";\n"
"ANSI_HIDE_CURSOR : String : \"\\x1b[?25l\";\n"
"ANSI_SHOW_CURSOR : String : \"\\x1b[?25h\";\n"
"ANSI_RESET       : String : \"\\x1b[0m\";\n"
"ANSI_ALT_BUFFER_ON : String : \"\\x1b[?1049h\";\n"
"ANSI_ALT_BUFFER_OFF : String : \"\\x1b[?1049l\";\n"
"\n"
"ANSI_FG_BLACK   : String : \"\\x1b[30m\";\n"
"ANSI_FG_RED     : String : \"\\x1b[31m\";\n"
"ANSI_FG_GREEN   : String : \"\\x1b[32m\";\n"
"ANSI_FG_YELLOW  : String : \"\\x1b[33m\";\n"
"ANSI_FG_BLUE    : String : \"\\x1b[34m\";\n"
"ANSI_FG_MAGENTA : String : \"\\x1b[35m\";\n"
"ANSI_FG_CYAN    : String : \"\\x1b[36m\";\n"
"ANSI_FG_WHITE   : String : \"\\x1b[37m\";\n"
"ANSI_FG_GRAY    : String : \"\\x1b[90m\";\n"
"\n"
"ANSI_BG_BLACK   : String : \"\\x1b[40m\";\n"
"ANSI_BG_RED     : String : \"\\x1b[41m\";\n"
"ANSI_BG_GREEN   : String : \"\\x1b[42m\";\n"
"ANSI_BG_YELLOW  : String : \"\\x1b[43m\";\n"
"ANSI_BG_BLUE    : String : \"\\x1b[44m\";\n"
"ANSI_BG_MAGENTA : String : \"\\x1b[45m\";\n"
"ANSI_BG_CYAN    : String : \"\\x1b[46m\";\n"
"ANSI_BG_WHITE   : String : \"\\x1b[47m\";\n"
"\n"
"ANSI_TEXT_BOLD : String : \"\\x1b[1m\";\n"
"\n"
"ConsoleConfigure :: func(raw_reads: Bool);\n"
"ConsoleWrite :: func(value: String);\n"
"ConsoleFlush :: func;\n"
"ConsoleRead :: func() -> String;\n"
"\n"
"// External Calls\n"
"\n"
"CallOutput :: struct {\n"
"    stdout: String;\n"
"}\n"
"\n"
"Call        :: func(command: String) -> (out: CallOutput, result: Result);\n"
"CallExe    :: func(path: String, arguments: String) -> (out: CallOutput, result: Result);\n"
"CallScript :: func(path: String, arguments: String, yov_arguments: String) -> (out: CallOutput, result: Result);\n"
"\n"
"// String Utils\n"
"\n"
"StrAppend       :: func(str0: String, str1: String) -> String;\n"
"StrEquals       :: func(str0: String, str1: String) -> Bool;\n"
"StrSplit        :: func(str: String, separator: String) -> Array[String];\n"
"StrGetCodepoint :: func(str: String, cursor: UInt) -> (codepoint: UInt, next_cursor: UInt);\n"
"StrFromCodepoint :: func(cp: UInt) -> String;\n"
"\n"
"PathAppend  :: func(path0: String, path1: String) -> String;\n"
"PathResolve :: func(path: String) -> String;\n"
"\n"
"// Time\n"
"\n"
"TimeTicks   :: func() -> UInt;\n"
"TimeElapsed :: func() -> Float;\n"
"\n"
"// Math\n"
"\n"
"MinI :: func(v0: Int, v1: Int) -> Int { return if v0 < v1 then v0 else v1; }\n"
"MaxI :: func(v0: Int, v1: Int) -> Int { return if v0 > v1 then v0 else v1; }\n"
"MinU :: func(v0: UInt, v1: UInt) -> UInt { return if v0 < v1 then v0 else v1; }\n"
"MaxU :: func(v0: UInt, v1: UInt) -> UInt { return if v0 > v1 then v0 else v1; }\n"
"MinF :: func(v0: Float, v1: Float) -> Float { return if v0 < v1 then v0 else v1; }\n"
"MaxF :: func(v0: Float, v1: Float) -> Float { return if v0 > v1 then v0 else v1; }\n"
"\n"
"Random :: func() -> UInt;\n"
"RandomRange :: func(min: Int, max: Int) -> Int;\n"
"Random01 :: func() -> Float;\n"
"\n"
"// Yov\n"
"\n"
"YovRequire     :: func(major: UInt, minor: UInt) -> Result;\n"
"YovRequireMin :: func(major: UInt, minor: UInt) -> Result;\n"
"YovRequireMax :: func(major: UInt, minor: UInt) -> Result;\n"
"\n"
"ObjectDefinition :: struct {\n"
"    identifier: String;\n"
"    type: Type;\n"
"    is_constant: Bool;\n"
"}\n"
"\n"
"FunctionDefinition :: struct {\n"
"    identifier: String;\n"
"    parameters: Array[ObjectDefinition];\n"
"    returns: Array[ObjectDefinition];\n"
"}\n"
"\n"
"StructDefinition :: struct {\n"
"    identifier: String;\n"
"    members: Array[ObjectDefinition];\n"
"}\n"
"\n"
"EnumDefinition :: struct {\n"
"    identifier: String;\n"
"    elements: Array[String];\n"
"    values: Array[Int];\n"
"}\n"
"\n"
"YovParseOutput :: struct {\n"
"    scripts: Array[String];\n"
"    functions: Array[FunctionDefinition];\n"
"    structs: Array[StructDefinition];\n"
"    enums: Array[EnumDefinition];\n"
"    globals: Array[ObjectDefinition];\n"
"    reports: Array[String];\n"
"}\n"
"\n"
"YovParse :: func(path: String) -> YovParseOutput;\n"
"\n"
"// User\n"
"AskYesNo :: func(text: String) -> Bool;\n"
"\n"
"// File System\n"
"\n"
"CopyMode :: enum {\n"
"    NoOverride,\n"
"    Override,\n"
"}\n"
"\n"
"FileInfo :: struct {\n"
"    path: String;\n"
"    is_directory: Bool;\n"
"}\n"
"\n"
"Exists      :: func(path: String) -> Bool;\n"
"DirCreate   :: func(path: String, recursive: Bool) -> Result;\n"
"DirDelete   :: func(path: String) -> Result;\n"
"DirCopy     :: func(dst: String, src: String) -> Result;\n"
"DirMove     :: func(dst: String, src: String) -> Result;\n"
"FileCopy    :: func(dst: String, src: String, mode: CopyMode) -> Result;\n"
"FileMove    :: func(dst: String, src: String) -> Result;\n"
"FileDelete  :: func(path: String) -> Result;\n"
"FileGetInfo :: func(path: String) -> (info: FileInfo, result: Result);\n"
"DirGetInfo  :: func(path: String) -> (infos: Array[FileInfo], result: Result);\n"
"\n"
"ReadEntireFile  :: func(path: String) -> (content: String, result: Result);\n"
"WriteEntireFile :: func(path: String, content: String) -> Result;\n"
"\n"
"// MSVC\n"
"\n"
"MsvcImportEnvX64 :: func() -> Result;\n"
"MsvcImportEnvX86 :: func() -> Result;\n"
"";