const char* YOV_CORE = ""
"\n"
"Result :: struct {\n"
"    failed: Bool;\n"
"    message: String;\n"
"    code: Int;\n"
"}\n"
"\n"
"YovInfo :: struct {\n"
"    path: String;\n"
"    version: String;\n"
"    major: Int;\n"
"    minor: Int;\n"
"    revision: Int;\n"
"}\n"
"\n"
"Type :: struct {\n"
"    name: String;\n"
"}\n"
"\n"
"Context :: struct {\n"
"    cd: String;\n"
"    script_dir: String;\n"
"    caller_dir: String;\n"
"    args: String[];\n"
"    types: Type[];\n"
"}\n"
"\n"
"OSKind :: enum {\n"
"    Windows, Linux\n"
"}\n"
"\n"
"OS :: struct {\n"
"    kind: OSKind;\n"
"}\n"
"\n"
"RedirectStdout :: enum {\n"
"    Console, Ignore, Script, ImportEnv\n"
"}\n"
"\n"
"CallsContext :: struct {\n"
"    redirect_stdout: RedirectStdout;\n"
"}\n"
"\n"
"// Core\n"
"\n"
"typeof  :: func(object: Any) -> Type;\n"
"print   :: func(object: Any);\n"
"println :: func(object: Any);\n"
"exit    :: func(exit_code: Int);\n"
"set_cd  :: func(cd: String) -> Result;\n"
"assert  :: func(result: Bool) -> Result;\n"
"failed :: func(message: String, exit_code: Int) -> Result;\n"
"\n"
"sleep :: func(millis: Int);\n"
"\n"
"env            :: func(name: String) -> (value: String, result: Result);\n"
"env_path       :: func(name: String) -> (value: String, result: Result);\n"
"env_path_array :: func(name: String) -> (value: String[], result: Result);\n"
"\n"
"// Console\n"
"\n"
"console_write :: func(value: String);\n"
"console_clear :: func;\n"
"\n"
"// External Calls\n"
"\n"
"CallOutput :: struct {\n"
"    stdout: String;\n"
"}\n"
"\n"
"call        :: func(command: String) -> (out: CallOutput, result: Result);\n"
"call_exe    :: func(path: String, arguments: String) -> (out: CallOutput, result: Result);\n"
"call_script :: func(path: String, arguments: String, yov_arguments: String) -> (out: CallOutput, result: Result);\n"
"\n"
"// String Utils\n"
"\n"
"path_resolve :: func(path: String) -> String;\n"
"str_get_codepoint :: func(str: String, cursor: Int) -> (codepoint: Int, next_cursor: Int);\n"
"str_split :: func(str: String, separator: String) -> String[];\n"
"\n"
"// JSON\n"
"\n"
"json_route :: func(json: String, route: String) -> (out: String, res: Result);\n"
"\n"
"// Yov\n"
"\n"
"yov_require     :: func(major: Int, minor: Int) -> Result;\n"
"yov_require_min :: func(major: Int, minor: Int) -> Result;\n"
"yov_require_max :: func(major: Int, minor: Int) -> Result;\n"
"\n"
"ObjectDefinition :: struct {\n"
"    identifier: String;\n"
"    type: Type;\n"
"    is_constant: Bool;\n"
"}\n"
"\n"
"FunctionDefinition :: struct {\n"
"    identifier: String;\n"
"    parameters: ObjectDefinition[];\n"
"    returns: ObjectDefinition[];\n"
"}\n"
"\n"
"StructDefinition :: struct {\n"
"    identifier: String;\n"
"    members: ObjectDefinition[];\n"
"}\n"
"\n"
"EnumDefinition :: struct {\n"
"    identifier: String;\n"
"    elements: String[];\n"
"    values: Int[];\n"
"}\n"
"\n"
"YovParseOutput :: struct {\n"
"    scripts: String[];\n"
"    functions: FunctionDefinition[];\n"
"    structs: StructDefinition[];\n"
"    enums: EnumDefinition[];\n"
"    globals: ObjectDefinition[];\n"
"    reports: String[];\n"
"}\n"
"\n"
"yov_parse :: func(path: String) -> YovParseOutput;\n"
"\n"
"// User\n"
"ask_yesno :: func(text: String) -> Bool;\n"
"\n"
"// File System\n"
"\n"
"CopyMode :: enum {\n"
"    NoOverride,\n"
"    Override,\n"
"}\n"
"\n"
"FileInfo :: struct {\n"
"    path: String;\n"
"    is_directory: Bool;\n"
"}\n"
"\n"
"exists             :: func(path: String) -> Bool;\n"
"create_directory   :: func(path: String, recursive: Bool) -> Result;\n"
"delete_directory   :: func(path: String) -> Result;\n"
"copy_directory     :: func(dst: String, src: String) -> Result;\n"
"move_directory     :: func(dst: String, src: String) -> Result;\n"
"copy_file          :: func(dst: String, src: String, mode: CopyMode) -> Result;\n"
"move_file          :: func(dst: String, src: String) -> Result;\n"
"delete_file        :: func(path: String) -> Result;\n"
"read_entire_file   :: func(path: String) -> (content: String, result: Result);\n"
"write_entire_file  :: func(path: String, content: String) -> Result;\n"
"file_get_info      :: func(path: String) -> (info: FileInfo, result: Result);\n"
"dir_get_files_info :: func(path: String) -> (infos: FileInfo[], result: Result);\n"
"\n"
"// MSVC\n"
"\n"
"msvc_import_env_x64 :: func() -> Result;\n"
"msvc_import_env_x86 :: func() -> Result;\n"
"";