const char* YOV_HELP_STR = ""
"Usage:\n"
"yov [language options] script_to_execute [script arguments]\n"
"\n"
"Language options:\n"
"    -analyze          analyzes the script without executing it.\n"
"    -trace            prints each line of code as it executes (for debugging/tracing purposes).\n"
"    -wait_end         displays a completion message and waits for the user to press ENTER before exiting.\n"
"    -user_assert      prompts the user for confirmation before performing any OS-level operation\n"
"                      (e.g. deleting a file).\n"
"    -no_user          disable all user prompts, automatically answer 'Yes' to all confirmations.\n"
"\n"
"Info options:\n"
"    -version, -v      displays the current version of Yov.\n"
"    -help, -h         shows this help message.\n"
"\n"
"Common Script Arguments:\n"
"    -help, -h         shows script help message, including its description and argument list.\n"
"\n"
"More information:\n"
"https://github.com/JoseRomaguera/Yov-Lang\n"
"";